name: Publish Go executables

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release matrix
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.21.4.linux-amd64.tar.gz"
        project_path: "./cmd/http-echo"
        binary_name: "http-echo"
        ldflags: "-w -s"
        pre_command: "go test ./... -covermode=atomic -coverpkg=./..."
        extra_files: LICENSE README.md
